// ==== TRANSLATIONS ====
const translations = {
  es: {
    'nav-home': 'Home',
    'nav-menu': 'Menú',
    'nav-location': 'Ubicación',
    'nav-contact': 'Contacto',
    'hero-title': 'Auténticos Mariscos Estilo Sinaloa',
    'hero-sub': 'Sabor del mar en el corazón de Salinas · Desde 2010',
    'hero-cta-menu': 'Ver Menú',
    'hero-cta-call': 'Llamar (831) 443-4010',
    'hero-scroll': 'Desliza',
    'badge-years': 'Años de sabor',
    'badge-fresh': 'Fresco cada día',
    'about-eyebrow': 'Nuestra Historia',
    'about-title': 'Tradición Sinaloense en Cada Bocado',
    'about-p1': 'Desde 2010, Mariscos Casa del Pollo trae a Salinas el auténtico sabor de la costa sinaloense. Nuestros aguachiles, chavelas y tacos gobernador son preparados diariamente con mariscos frescos y recetas familiares que han conquistado paladares por más de una década.',
    'about-p2': 'Somos más que un restaurante: somos una tradición. Nuestras tortillas de maíz se hacen a mano, nuestras salsas se muelen cada mañana y cada plato lleva el cariño de familia.',
    'feat1-t': 'Mariscos Frescos',
    'feat1-p': 'Camarón, pulpo, pescado y más, seleccionados a diario.',
    'feat2-t': 'Recetas Auténticas',
    'feat2-p': 'Sabor sinaloense que solo abuelas y familia conocen.',
    'feat3-t': 'Chavelas & Micheladas',
    'feat3-p': 'Nuestras bebidas insignia, pura tradición del norte.',
    'about-since': 'Sirviendo desde',
    'menu-eyebrow': 'Nuestro Menú',
    'menu-title': 'Los Favoritos de la Casa',
    'menu-sub': 'Platillos que nuestros clientes piden una y otra vez',
    'dish1': 'Camarón curtido, pepino, aguacate y salsa. La joya de la casa.',
    'dish2': '3 tacos de camarón cocido, queso, aguacate y cebolla. Un clásico.',
    'dish3': 'Camarón cocido, pico de gallo y pepino.',
    'dish4': 'Mojarra entera frita con arroz, papas fritas, ensalada y tortillas.',
    'dish5': 'Camarón cocido, camarón curtido, pepino y cebolla. Perfecta para compartir.',
    'dish6': '3 empanadas doradas de camarón con ensalada y salsa.',
    'dish7': 'Aguachile de camarón sobre tostada crujiente.',
    'dish8': 'Carne, papas fritas, frijoles, queso, pico de gallo, crema y guacamole.',
    'tag-signature': '⭐ Especialidad',
    'tag-popular': '🔥 Popular',
    'tag-share': '🍽️ Para compartir',
    'menu-full': '¿Quieres ver el menú completo con más de 100 platillos?',
    'menu-full-btn': 'Menú Completo',
    'menu-order': 'Ordenar Delivery',
    'gallery-eyebrow': 'Galería',
    'gallery-title': 'Sabor en Cada Foto',
    'gallery-sub': 'Síguenos en redes para ver más',
    'reserve-eyebrow': 'Reservaciones',
    'reserve-title': 'Reserva tu mesa en segundos',
    'reserve-sub': 'Llámanos con la fecha, hora y número de personas. Te confirmamos al instante.',
    'reserve-btn': 'Llamar (831) 443-4010',
    'hours-title': 'Horarios',
    'day-mon': 'Lunes', 'day-tue': 'Martes', 'day-wed': 'Miércoles', 'day-thu': 'Jueves',
    'day-fri': 'Viernes', 'day-sat': 'Sábado', 'day-sun': 'Domingo',
    'delivery-eyebrow': 'Delivery',
    'delivery-title': 'Recíbelo en Casa',
    'delivery-sub': 'Ordena por tu app favorita',
    'delivery-direct': 'SIN COMISIÓN',
    'delivery-web': 'Pedido Directo',
    'delivery-call': 'Llamar →',
    'order': 'Ordenar →',
    'location-eyebrow': 'Visítanos',
    'location-title': '¿Dónde estamos?',
    'loc-address': 'Dirección',
    'loc-phone': 'Teléfono',
    'loc-parking': 'Estacionamiento',
    'loc-parking-p': 'Gratuito · Accesible en silla de ruedas',
    'loc-payment': 'Formas de pago',
    'loc-payment-p': 'Efectivo · Tarjeta de crédito y débito',
    'loc-directions': 'Cómo llegar',
    'footer-tag': 'Auténtico sabor sinaloense en Salinas desde 2010.',
    'footer-nav': 'Menú',
    'footer-contact': 'Contacto',
    'footer-social': 'Síguenos',
    'social-note': 'También en Yelp, Google & DoorDash',
    'footer-rights': 'Todos los derechos reservados.',
    'footer-dev': 'Sitio hecho con ❤️ por ENT-CODE'
  },
  en: {
    'nav-home': 'Home',
    'nav-menu': 'Menu',
    'nav-location': 'Location',
    'nav-contact': 'Contact',
    'hero-title': 'Authentic Sinaloa-Style Seafood',
    'hero-sub': 'Ocean flavors in the heart of Salinas · Since 2010',
    'hero-cta-menu': 'View Menu',
    'hero-cta-call': 'Call (831) 443-4010',
    'hero-scroll': 'Scroll',
    'badge-years': 'Years of flavor',
    'badge-fresh': 'Fresh daily',
    'about-eyebrow': 'Our Story',
    'about-title': 'Sinaloa Tradition in Every Bite',
    'about-p1': 'Since 2010, Mariscos Casa del Pollo has brought the authentic taste of the Sinaloa coast to Salinas. Our aguachiles, chavelas, and tacos gobernador are prepared daily with fresh seafood and family recipes that have won hearts for over a decade.',
    'about-p2': 'We are more than a restaurant — we are a tradition. Our corn tortillas are made by hand, our salsas are ground every morning, and every dish carries family love.',
    'feat1-t': 'Fresh Seafood',
    'feat1-p': 'Shrimp, octopus, fish and more, selected daily.',
    'feat2-t': 'Authentic Recipes',
    'feat2-p': 'Sinaloa flavor that only grandmas and family know.',
    'feat3-t': 'Chavelas & Micheladas',
    'feat3-p': 'Our signature drinks — pure northern tradition.',
    'about-since': 'Serving since',
    'menu-eyebrow': 'Our Menu',
    'menu-title': 'House Favorites',
    'menu-sub': 'Dishes our guests order again and again',
    'dish1': 'Lime-cured shrimp, cucumber, avocado and salsa. The jewel of the house.',
    'dish2': '3 tacos with cooked shrimp, cheese, avocado and onion. A classic.',
    'dish3': 'Cooked shrimp, pico de gallo and cucumber.',
    'dish4': 'Whole fried tilapia with rice, french fries, salad and tortillas.',
    'dish5': 'Cooked shrimp, cured shrimp, cucumber and onion. Perfect for sharing.',
    'dish6': '3 golden shrimp empanadas with salad and salsa.',
    'dish7': 'Shrimp aguachile on a crispy tostada.',
    'dish8': 'Meat, french fries, beans, cheese, pico de gallo, sour cream and guacamole.',
    'tag-signature': '⭐ Signature',
    'tag-popular': '🔥 Popular',
    'tag-share': '🍽️ To Share',
    'menu-full': 'Want to see the full menu with 100+ dishes?',
    'menu-full-btn': 'Full Menu',
    'menu-order': 'Order Delivery',
    'gallery-eyebrow': 'Gallery',
    'gallery-title': 'Flavor in Every Photo',
    'gallery-sub': 'Follow us on social for more',
    'reserve-eyebrow': 'Reservations',
    'reserve-title': 'Book Your Table in Seconds',
    'reserve-sub': 'Call us with the date, time, and party size. We confirm instantly.',
    'reserve-btn': 'Call (831) 443-4010',
    'hours-title': 'Hours',
    'day-mon': 'Monday', 'day-tue': 'Tuesday', 'day-wed': 'Wednesday', 'day-thu': 'Thursday',
    'day-fri': 'Friday', 'day-sat': 'Saturday', 'day-sun': 'Sunday',
    'delivery-eyebrow': 'Delivery',
    'delivery-title': 'Get It Delivered',
    'delivery-sub': 'Order from your favorite app',
    'delivery-direct': 'NO FEES',
    'delivery-web': 'Order Direct',
    'delivery-call': 'Call →',
    'order': 'Order →',
    'location-eyebrow': 'Visit Us',
    'location-title': 'Where to Find Us',
    'loc-address': 'Address',
    'loc-phone': 'Phone',
    'loc-parking': 'Parking',
    'loc-parking-p': 'Free · Wheelchair accessible',
    'loc-payment': 'Payment',
    'loc-payment-p': 'Cash · Credit and debit cards',
    'loc-directions': 'Get Directions',
    'footer-tag': 'Authentic Sinaloa flavor in Salinas since 2010.',
    'footer-nav': 'Menu',
    'footer-contact': 'Contact',
    'footer-social': 'Follow Us',
    'social-note': 'Also on Yelp, Google & DoorDash',
    'footer-rights': 'All rights reserved.',
    'footer-dev': 'Built with ❤️ by ENT-CODE'
  }
};

// ==== LANGUAGE TOGGLE ====
let currentLang = Site.getStoredLang();

function applyLang(lang) {
  currentLang = Site.setLang(lang);
  Site.applyTranslations(translations, currentLang);
}

applyLang(currentLang);
Site.bindLanguageToggle(() => currentLang, applyLang);
Site.bindNavbar();
Site.bindMobileNav();
Site.bindReveal('.section-head, .dish, .feat, .gallery-item, .delivery-card, .loc-block');
Site.setCurrentYear();
